export const words = [
    "Bar",
    "Fire",
    "Grill",
    "Drive Thru",
    "Place",
    "Best",
    "Spot",
    "Prime",
    "Eatin'",
];

export const cities = [
    "Albuquerque",
    "Arlington",
    "Atlanta",
    "Austin",
    "Baltimore",
    "Boston",
    "Charlotte",
    "Chicago",
    "Cleveland",
    "Colorado Springs",
    "Columbus",
    "Dallas",
    "Denver",
    "Detroit",
    "El Paso",
    "Fort Worth",
    "Fresno",
    "Houston",
    "Indianapolis",
    "Jacksonville",
    "Kansas City",
    "Las Vegas",
    "Long Island",
    "Los Angeles",
    "Louisville",
    "Memphis",
    "Mesa",
    "Miami",
    "Milwaukee",
    "Nashville",
    "New York",
    "Oakland",
    "Oklahoma",
    "Omaha",
    "Philadelphia",
    "Phoenix",
    "Portland",
    "Raleigh",
    "Sacramento",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "Tucson",
    "Tulsa",
    "Virginia Beach",
    "Washington",
];

export const categories = [
    "Brunch",
    "Burgers",
    "Coffee",
    "Deli",
    "Dim Sum",
    "Indian",
    "Italian",
    "Mediterranean",
    "Mexican",
    "Pizza",
    "Ramen",
    "Sushi",
];

export const ratings = [
    {
        rating: 1,
        text: "Would never eat here again!",
    },
    {
        rating: 2,
        text: "Not my cup of tea.",
    },
    {
        rating: 3,
        text: "Exactly okay :/",
    },
    {
        rating: 4,
        text: "Actually pretty good, would recommend!",
    },
    {
        rating: 5,
        text: "This is my favorite place. Literally.",
    },
];

export const data = {
    words,
    cities,
    categories,
    ratings,
};
